[libraries]
spring-boot-test    = { module="org.springframework.boot:spring-boot-starter-test" }
mockito             = "org.mockito.kotlin:mockito-kotlin:4.0.0"
reactor-test        = "io.projectreactor:reactor-test:3.4.14"

[bundles]
testDependencies    = ["spring-boot-test", "mockito", "reactor-test"]